name: ranked_positional_method
description: An App Made by Makesh Vineeth.

publish_to: 'none' 
version: 2.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  clipboard: ^0.1.2+8
  cupertino_icons: ^1.0.1
  flutter_fadein: ^2.0.0
  flutter_launcher_icons: ^0.8.1
  flutter_rename_app: ^1.0.0
  peanut: ^3.5.1
  theme_provider: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_rename_app:
  application_name: Calculate RPW
  dart_package_name: ranked_positional_method
  application_id: com.makeshtech.rpw
  bundle_id: com.makeshtech.rpw

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/